### PR TITLE
updating the database before seed depolyment and api tests 

### PR DESCRIPTION
**Pull request by developer22-university**
i faced this error hope it helps

### CODE REVIEW

**Comment by developer22-university** [comment]
i was able to perform deployment tests after this, i am using Ubuntu, hope this helps

**Comment by developer22-university** [comment]
@olleolleolle

**Comment by olleolleolle** [comment]
This [Thoughtbot blogpost about the `bin/setup` file](https://thoughtbot.com/blog/bin-setup) has an example of using `bin/setup`.

> Regardless of the bin/setup file’s contents, a developer should be able to clone the project and run a single, consistent, reliable command to start contributing.

Referring to that (already-existing in this project) script _could_ make some of the instruction shorter.

What do you think about that?

PS: I get all the notifications, no need to ping my username to make me aware of changes.

**Comment by nynnejc** [comment]
Hi @developer22-university I have repeatedly asked that applicants for RGSoC wait to contribute to this project until after the committee has selected the official team. I will write this as a comment in the project page as well. We would like to focus on helping all the teams apply and then add contributors who still want to take part after the team has been selected.

**Comment by sibsmc** [comment]
Aged pull request which fails tests. New pull request should be created to make these changes if they are required.

**Pull request closed without merging**
