### PR TITLE
Gemfile cleanup

### PR DESCRIPTION
**Pull request by kaspth**

### CODE REVIEW

**Comment by olleolleolle** [comment]
Aren't we using PG at all?

**Comment by kaspth** [comment]
Not as far as I could see, but I only looked in config/database.yml

**Comment by kaspth** [comment]
@olleolleolle informed me in person, that pg is probably used in a Heroku deploy, so I've rebased out that removal.

**Comment by kaspth** [comment]
Looks like cutting all the needless gems took the uncached bundle install times down to a little over a minute: https://travis-ci.com/github/RailsGirlsCPH/mentor-mentee-platform/builds/153294603#L224

**Comment by olleolleolle** [comment]
Let's get this change merged - we will need the speedups. 

When and if we get to a place where we need the gems removed, we will add them back, if needed. Until then, let us enjoy the quick feedback cycle.

**Comment by kaspth** [comment]
Cool cool, I can’t merge, so someone else will have to do that 😄✌️

**Comment by olleolleolle** [comment]
Alright, done, thanks!

**Pull request merged**
